### ISSUE TITLE
unable to install processrunner project

### ISSUE THREAD

**Issue by egirdhar** [fortify-ps/FortifyBugTrackerUtility#32]
Hi, 

While running mvn clean install for project - processrunner , it throws the following error..

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project processrunner: Compilation failure
[ERROR] /C:/Users/TEMP.INTNP/Downloads/FortifyBugTrackerUtility-master/FortifyBugTrackerUtility-master/processrunner/src/main/java/com/fortify/processrunner/RunProcessRunnerFromCLI.java:[40,30] cannot find symbol
[ERROR] symbol:   class LogMaskingConverter
[ERROR] location: package com.fortify.util.log4j
[ERROR] -> [Help 1]
[ERROR] 

Could you help where I can get the corresponding classes/ Jar files  ?

**Comment by rsenden** [comment]
RunProcessRunnerFromCLI.java in the current master branch doesn't contain any reference to LogMaskingConverter, so which version of FortifyBugTrackerUtility are you trying to build?

I would suggest getting the latest master branch or the latest tagged release, and try to build that.

Also note that usually you shouldn't be building or installing individual modules; you should simply run a `mvn clean package` in the root directory. This will automatically build all modules, including processrunner.
