### ISSUE TITLE
Username Password

### ISSUE THREAD

**Issue by oaldahir** [fortify-ps/FortifyBugTrackerUtility#39]
For the"test plugin" pop up window:

Change From:
Enter your username and password for logging into Jira. These credentials will be used to test the configuration for Jira. These are not your Fortify Software Security Center credentials.

To:
Enter your username and password for logging into Jira. For Jira Cloud use api token in place of your password. These credentials will be used to test the configuration for Jira.  These are not your Fortify Software Security Center credentials.

**Comment by rsenden** [comment]
FortifyBugTrackerUtility is a stand-alone utility that retrieves vulnerabilities from FoD or SSC, and submits those vulnerabilities to a bug tracker or other external system.

Although it serves a similar purpose as the bug tracking integration functionality provided by SSC, from a technical perspective FortifyBugTrackerUtility is not at all related to the bug tracking integration functionality provided by SSC.

Any issues or change requests related to the bug tracking integration functionality provided by SSC will need to be submitted through Fortify support channels.
