### ISSUE TITLE
SSC - JIRA 8 Integration

### ISSUE THREAD

**Issue by ParthibanSG** [fortify-ps/FortifyBugTrackerUtility#40]
I am trying to integrate my JIRA instance which is in 8.5.1 version and the default MicroFocus utility for bug tracking supports till JIRA 7.11

Could you please let me know if JIRA 8 can be integrated with SSC and I am looking for scenario as stated below

- When a FPR is uploaded to SSC, JIRA should have 4 defects filed based on the category (Critical, High, Medium, Low)

Thanks

**Comment by rsenden** [comment]
FortifyBugTrackerUtility is a stand-alone utility that retrieves vulnerabilities from FoD or SSC, and submits those vulnerabilities to a bug tracker or other external system.

Although it serves a similar purpose as the bug tracking integration functionality provided by SSC, from a technical perspective FortifyBugTrackerUtility is not at all related to the bug tracking integration functionality provided by SSC.

It looks like you are referring to the JIRA bug tracker plugin provided by SSC, as FortifyBugTrackerUtility doesn't specifically state which JIRA versions are supported.

Despite what is stated in any documentation, both the built-in SSC integration and FortifyBugTrackerUtility may successfully work with JIRA 8; you will need to try yourself.

If FortifyBugTrackerUtility doesn't properly work with a specific (recent) JIRA version, please submit a new bug in this GitHub project.

Any issues or change requests related to the bug tracking integration functionality provided by SSC will need to be submitted through Fortify support.
