### ISSUE TITLE
Support for Azure DevOps

### ISSUE THREAD

**Issue by micro-focus** [fortify-ps/FortifyBugTrackerUtility#44]
Integration with Azure DevOps is not as straightforward or seamless as TFS. The following changes had to be made in order for the utility to work with ADO:

* Generate a personal access token and use it for the `-TFSPassword` option. (Personal access tokens can be generated in the ADO portal by clicking on the user settings icon in the top-right corner and clicking on "Personal access tokens".)
* For the `-TFSBaseUrl` option, use `https://dev.azure.com/{organization}`. For instance, if your organization name is `piedpiper`, use `https://dev.azure.com/piedpiper`.
* For the `-TFSCollection` option, use `/`.
* In `FoDToTFS.xml`, copy the `<entry key="System.Description">` element from the `appendedFields` property to the `fields` property. Otherwise, `System.Description` doesn't get picked up. For example:
```xml
<property name="fields"><map>
	<entry key="System.Title" value="FoD Detected ${category} at ${primaryLocationFull}"/>
	<entry key="Microsoft.VSTS.Common.Severity" value="${{'Critical':'1 - Critical','High':'2 - High','Medium':'3 - Medium','Low':'4 - Low'}.get(severityString)}"/>
	<entry key="Microsoft.VSTS.TCM.ReproSteps" value="--- Changes to the description will be overwritten when FortifyBugTrackerUtility updates issues states ---\n\nCategory: ${category} at ${primaryLocationFull}"/>
	<entry key="System.Description"><value><![CDATA[
		<br/>\n<br/>\nId: ${id}<br/>\nState: ${vulnState}<br/>\nLine: ${lineNumber?:'Unknown'}<br/>\nLink: <a href="${deepLink}">${deepLink}</a>
	]]></value></entry>
</map></property>

<property name="appendedFields"><map>
	<entry key="System.Description"><value><![CDATA[
		<br/>\n<br/>\nId: ${id}<br/>\nState: ${vulnState}<br/>\nLine: ${lineNumber?:'Unknown'}<br/>\nLink: <a href="${deepLink}">${deepLink}</a>
	]]></value></entry>
</map></property>
```

**Comment by bars0um** [comment]
Ah! Nice work! Will try this now... was bashing my head at this for quite a bit...

**Comment by bars0um** [comment]
On latest version of Azure I think you need to use Microsoft.VSTS.TCM.SystemInfo instead of System.Description for this to work properly

**Comment by rsenden** [comment]
Some additional notes regarding which TFS/ADO field to use for the issue description:

* Which field to use to store the issue description depends on the work item type
* I haven't checked recently, but in older TFS/ADO versions you had to use `Microsoft.VSTS.TCM.ReproSteps` if `workItemType` was set to `Bug`, and `System.Description` for other work item types
* Setting the wrong field wouldn't cause any errors while submitting the vulnerabilities, but the description would simply not be easily visible in TFS/ADO (you could only see the value by looking at the list of changed fields in the work item history)
* Basically you should just look at what field is being displayed by TFS/ADO for a particular work item type, and use the identifier for that field to set the issue description in FortifyBugTrackerUtility configuration

With regards to the FortifyBugTrackerUtility configuration:

* You should use the same description field in both `fields` and `appendedFields`, so both should have either `Microsoft.VSTS.TCM.ReproSteps`, `System.Description`, or `Microsoft.VSTS.TCM.SystemInfo` as mentioned by Mr. bars0um
* The shipped FoDToTFS.xml contains a bug, as the `System.Description` field listed in `appendedFields` does not match any fields listed in `fields`

The correct configuration would be as follows, replacing `!!!workItemType!!!` (1 occurence) and `!!!descriptionFieldIdForWorkItemType!!!` (2 occurrences) with a valid ADO work item and and corresponding description field identifier respectively:

```xml
		<property name="workItemType" value="!!!workItemType!!!"/>
		
		<property name="groupTemplateExpression" value="${category}+${primaryLocationFull}"/>
	
		<property name="fields"><map>
			<entry key="System.Title" value="FoD Detected ${category} at ${primaryLocationFull}"/>
			<entry key="Microsoft.VSTS.Common.Severity" value="${{'Critical':'1 - Critical','High':'2 - High','Medium':'3 - Medium','Low':'4 - Low'}.get(severityString)}"/>
			<entry key="!!!descriptionFieldIdForWorkItemType!!!" value="--- Changes to the description will be overwritten when FortifyBugTrackerUtility updates issues states ---\n\nCategory: ${category} at ${primaryLocationFull}"/>
		</map></property>

		<property name="appendedFields"><map>
			<entry key="!!!descriptionFieldIdForWorkItemType!!!"><value><![CDATA[
				<br/>\n<br/>\nId: ${id}<br/>\nState: ${vulnState}<br/>\nLine: ${lineNumber?:'Unknown'}<br/>\nLink: <a href="${deepLink}">${deepLink}</a>
			]]></value></entry>
		</map></property>
```

**Comment by bars0um** [comment]
Just wanted to update this in case someone else runs into this issue. 

We had an issue where the configuration was leading to a Bad response from the Azure API with no clear description of the error:

```
Bad Request, response contents:
{"$id":"1","innerException":null,"message":"Value cannot be null.","typeName":"Microsoft.VisualStudio.Services.Common.VssPropertyValidationException, Microsoft.VisualStudio.Services.Common, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"VssPropertyValidationException","errorCode":0,"eventId":3000}
```

The error would only be resolved if we used the  < entry>< value>XXX< /value>< /entry> for defining the !!!descriptionFieldIdForWorkItemType!!! variable. 

So for our example, the following did __not__ work:

```
<entry key="Microsoft.VSTS.TCM.ReproSteps" value="--- Changes to the description will be overwritten when FortifyBugTrackerUtility updates issues states ---\n\nCategory: ${category} at ${primaryLocationFull}"/>
```

While this did:

```
<entry key="Microsoft.VSTS.TCM.ReproSteps"><value><![CDATA[ my test text ]]></value></entry>
```

**Comment by bars0um** [comment]
We had an issue where the configuration was leading to a Bad response from the Azure API with no clear description of the error:

```
Bad Request, response contents:
{"$id":"1","innerException":null,"message":"Value cannot be null.","typeName":"Microsoft.VisualStudio.Services.Common.VssPropertyValidationException, Microsoft.VisualStudio.Services.Common, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"VssPropertyValidationException","errorCode":0,"eventId":3000}
```

It appears to happen if we mistakenly place required fields in the appendedFields section instead of the fields section.

**Comment by rsenden** [comment]
A new [4.2-beta pre-release](https://github.com/fortify-ps/FortifyBugTrackerUtility/releases/tag/4.2-beta) has been posted, which contains major updates related to Azure DevOps support. Most of the information in this thread is now obsolete. Please open a new issue if you encounter any problems with the new beta version.
