### ISSUE TITLE
SSC to ADO BugState Sync Failure: ERROR com.fortify.bugtracker.common.tgt.processor.AbstractTargetProcessorUpdateIssues 

### ISSUE THREAD

**Issue by Ri7Sh** [fortify-ps/FortifyBugTrackerUtility#51]
SSC to ADO WorkItem update fails for issues

env:
Fortify Version - 20.1.2
Jdk1.8.0_281

> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Target Issue Locator Id is: [null]
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Target Issue Locator Id is: [null]
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Deep link is: [https://<organization>.visualstudio.com/<projectid>/_workitems/edit/<workitemid>]
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Deep link is: [https://<organization>.visualstudio.com/<projectid>/_workitems/edit/<workitemid>]
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Params Count is 0
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Params Count is 0
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Got the id from the deepLinkUrl. The length is  and  id is <workitemid>
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Got the id from the deepLinkUrl. The length is  and  id is <workitemid>
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Id that is returned is: <workitemid>
> 2021-03-06 02:30:42,786 [main] WARN com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection - Id that is returned is: <workitemid>
> 2021-03-06 02:30:43,005 [main] ERROR com.fortify.bugtracker.common.tgt.processor.AbstractTargetProcessorUpdateIssues - [TFS] Error updating issue https://<organization>.visualstudio.com/<projectid>/_workitems/edit/<workitemid>
> javax.ws.rs.ProcessingException: Error closing message content input stream.
> 	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:138) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:132) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.glassfish.jersey.message.internal.InboundMessageContext.close(InboundMessageContext.java:915) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.glassfish.jersey.client.InboundJaxrsResponse.close(InboundJaxrsResponse.java:143) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.util.rest.connection.AbstractRestConnection.getSuccessfulResponse(AbstractRestConnection.java:400) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.util.rest.connection.AbstractRestConnection.checkResponseAndGetOutput(AbstractRestConnection.java:373) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:224) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:190) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.tgt.tfs.connection.TFSRestConnection.updateIssueData(TFSRestConnection.java:88) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.tgt.tfs.processor.TFSTargetProcessorUpdateIssuesWithTransitions$1.updateIssueFields(TFSTargetProcessorUpdateIssuesWithTransitions.java:69) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.common.tgt.processor.AbstractTargetProcessorUpdateIssues.updateIssueFieldsIfNecessary(AbstractTargetProcessorUpdateIssues.java:185) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.common.tgt.processor.AbstractTargetProcessorUpdateIssues.processMap(AbstractTargetProcessorUpdateIssues.java:112) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessorBuildObjectMapFromGroupedObjects.processGroup(AbstractProcessorBuildObjectMapFromGroupedObjects.java:71) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessorGroupByExpressions.postProcess(AbstractProcessorGroupByExpressions.java:168) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:102) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:82) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.common.src.processor.AbstractSourceProcessorRetrieveVulnerabilities.process(AbstractSourceProcessorRetrieveVulnerabilities.java:79) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:101) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:82) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.bugtracker.common.src.processor.AbstractSourceVulnerabilityProcessor.process(AbstractSourceVulnerabilityProcessor.java:88) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractCompositeProcessor.processForAll(AbstractCompositeProcessor.java:112) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractCompositeProcessor.process(AbstractCompositeProcessor.java:85) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:101) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:82) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.AbstractProcessRunner.process(AbstractProcessRunner.java:70) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.AbstractProcessRunner.run(AbstractProcessRunner.java:55) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.run(RunProcessRunnerFromSpringConfig.java:85) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.RunProcessRunnerFromCLI.run(RunProcessRunnerFromCLI.java:166) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.processrunner.RunProcessRunnerFromCLI.main(RunProcessRunnerFromCLI.java:359) [FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> Caused by: javax.net.ssl.SSLException: Connection has closed: javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
> 	at sun.security.ssl.SSLSocketImpl$AppInputStream.checkEOF(SSLSocketImpl.java:992) ~[?:1.8.0_281]
> 	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:883) ~[?:1.8.0_281]
> 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:97) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at java.io.BufferedInputStream.close(BufferedInputStream.java:483) ~[?:1.8.0_281]
> 	at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[?:1.8.0_281]
> 	at com.fortify.util.rest.connection.connector.ApacheConnector$2.close(ApacheConnector.java:654) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[?:1.8.0_281]
> 	at com.fortify.util.rest.connection.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:631) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:135) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	... 28 more
> Caused by: javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:133) ~[?:1.8.0_281]
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:1.8.0_281]
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:340) ~[?:1.8.0_281]
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296) ~[?:1.8.0_281]
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:287) ~[?:1.8.0_281]
> 	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:737) ~[?:1.8.0_281]
> 	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:716) ~[?:1.8.0_281]
> 	at org.apache.http.impl.BHttpConnectionBase.close(BHttpConnectionBase.java:325) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.conn.CPoolEntry.closeConnection(CPoolEntry.java:70) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.conn.CPoolProxy.close(CPoolProxy.java:86) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.execchain.ConnectionHolder.releaseConnection(ConnectionHolder.java:103) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.execchain.ConnectionHolder.close(ConnectionHolder.java:156) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.apache.http.impl.execchain.HttpResponseProxy.close(HttpResponseProxy.java:62) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at com.fortify.util.rest.connection.connector.ApacheConnector$2.close(ApacheConnector.java:653) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[?:1.8.0_281]
> 	at com.fortify.util.rest.connection.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:631) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:135) ~[FortifyBugTrackerUtility-3.10-SNAPSHOT.jar:?]
> 	... 28 more

**Comment by rsenden** [comment]
Some questions and comments:

- The URL's/deep links listed in the log look odd; did you remove sensitive data like instance/hostname and work item id?
- Is this error reproducible, or could it have been caused by a temporary connection issue?
- You are using an older snapshot version of FortifyBugTrackerUtility; please verify whether the same error occurs with the latest release version

**Comment by Ri7Sh** [comment]
@rsenden 

- Yes, I removed sensitive data from above logs
- I expected it to be caused by temporary connection issue, but the error occurs for few work items only. For those workitems, it is reproducible. But, I couldn't find out what exact issue on those workitems is causing this.
- I updated the FortifyBugTrackerUtility to Release 4.1 - which causes `[https://github.com/fortify-ps/FortifyBugTrackerUtility/issues/49](url)`. As per your comment on that issue, I have updated the utility to `[https://github.com/fortify-ps/FortifyBugTrackerUtility/commit/6712675075b164434d8dfaa0359ee84117414406](url)`, but this is causing another error while fetching the issues from the Application Version `{"message":"Malformed Logical Filter String, check AND and OR syntax in expression: '[all_search_fields]:FOLDER:94dfe6d3-59f8-4b38-bd13-7034b7caa470 AND [adobuglink]:&amp;lt;none&amp;gt;'","responseCode":400,"errorCode":-1}`

**Comment by rsenden** [comment]
@Ri7Sh Individual commits may be fixing individual issues, but that doesn't mean that a particular commit actually results in a working version of the utility. I've done a lot of other updates related to ADO after that particular commit, and have since posted a [4.2-beta pre-release](https://github.com/fortify-ps/FortifyBugTrackerUtility/releases/tag/4.2-beta).

Can you please test with this beta release and let me know if you encounter any issues? Note that you will need to make some changes to configuration and command line parameters as detailed in the documentation:

* Configuration files have been updated:
    * `FoDToTFS.xml` renamed to `FoDToADO.xml`
    * `SSCToTFS.xml` renamed to `SSCToADO.xml`
    * Various fixes and improvements related to field definitions and transitions 
* Command line options have been updated:
    * All command line options starting with `-TFS` now start with `-ADO`
    * The `-TFSCollection` option has been removed; the collection or organization should now be included in the base URL
    * The `-TFSUserName` and `-TFSPassword` options have been replaced by the single `-ADOPAT` option to authenticate with a Personal Access Token
* Where relevant, names for storing bug links have been updated:
    * When storing bug links in comments for FoD, you may want to set the `commentTargetName` property to `TFS` in the `FoDToADO.xml` configuration file, in order for the utility to pick up any previously existing bug links
    * When storing bug links in a custom tag for SSC, you may want to rename the custom tag to `ADOBugLink` or update `SSCToADO.xml` to use `TFSBugLink` instead of `ADOBugLink`
    
Various other fixes and improvements have been implemented, for example to prevent unnecessary updates of the
work item description in Azure DevOps if the vulnerability data hasn't changed.

**Comment by rsenden** [comment]
Given that you have opened new issue #54 for this 'Malformed Logical Filter String' error, I guess this issue can be closed?
