### ISSUE TITLE
Bidirectional Sync Support for FoD

### ISSUE THREAD

**Issue by sanjeev30** [fortify-ps/FortifyBugTrackerUtility#55]
As of now Bidirectional sync support for this utility is available for SSC to different Bug Trackers which synchronizes the states of the reported bug on the fortify and bug trackers . Is it possible to also include this feature for the FoD to Bug Trackers(like ADO)?

**Comment by rsenden** [comment]
SSC allows for defining custom tags that can be used to store arbitrary data like bug tracker state at vulnerability level. FoD doesn't provide this functionality, hence bidirectional sync is not supported on FoD.
