### ISSUE TITLE
Help Needed: Applying multiple tags to AzureDevOps Bug

### ISSUE THREAD

**Issue by msadiq-h** [fortify-ps/FortifyBugTrackerUtility#56]
How can we apply multiple tags while creating bug in AzureDevOps. I am using below mentioned line of code in config file to apply single tag.

entry key="System.Tags" value="#TESTTag;"

**Comment by rsenden** [comment]
Just use semicolon-separated tags, like the following:

`<entry key="System.Tags" value="Tag1; Tag2; Tag3"/>`
