### ISSUE TITLE
Non-Zero Return Code for failures

### ISSUE THREAD

**Issue by bars0um** [fortify-ps/FortifyBugTrackerUtility#58]
At present the utility will always return a zero return code regardless of whether errors were thrown or not. This results in a successful pipeline run on CI systems running a sync job despite errors being thrown. 

Ideally failures and exceptions should result in a non-zero return code.

**Comment by rsenden** [comment]
The utility already returned exit code 1 if there was a major error, for example when the utility is unable to connect to the source system. Potentially transient errors, for example if an error occurs while processing a single vulnerability, are logged but the utility continues processing other vulnerabilities. The next release of the utility will now return exit code 2 on such potentially transient errors.

**Comment by rsenden** [comment]
https://github.com/fortify-ps/FortifyBugTrackerUtility/releases/tag/4.3
