### ISSUE TITLE
SSC Custom Tag updated and message added when Bug is not updated

### ISSUE THREAD

**Issue by Ri7Sh** [fortify-ps/FortifyBugTrackerUtility#59]
@rsenden, with FortifyBugUtility-4.2, we are seeing that ADOBugState update messages are added with each bug utility run even when the ADO Bug was closed long ago or no action is taken by the user. Meanwhile, the correct behaviour would be only update custom tag when there is a change from older tag. 

1. ![image](https://user-images.githubusercontent.com/21293001/117339047-e8ef1780-aebc-11eb-9bbf-9384686040ef.png)

2. ![image](https://user-images.githubusercontent.com/21293001/117339755-bb569e00-aebd-11eb-9fb2-8a60c3b39ca5.png)

**Comment by Ri7Sh** [comment]
@rsenden is there any update on this?

**Comment by rsenden** [comment]
Unfortunately I don't have time to look into this right now as I'm very busy with customer engagements. I hope to have some time to look into this somewhere in the coming 2-3 weeks.

I think the utility just invokes the SSC API to set the tag value, without taking into account whether the custom tag was already set to that same value. I didn't consider that this would add a message to the issue history on every run (I assume this is why you reported this issue, correct?).

So either the utility should check the existing value before updating it, or SSC shouldn't add the history message if the custom tag isn't actually being changed. I'll need to think about and discuss with the SSC team what would be the best option.

Please ping me again if you haven't heard back in about 2 weeks.

**Comment by Ri7Sh** [comment]
I can take up and work on this issue if that is okay with the team.

**Comment by rsenden** [comment]
Fix will be included in next release

**Comment by rsenden** [comment]
https://github.com/fortify-ps/FortifyBugTrackerUtility/releases/tag/4.3
