### ISSUE TITLE
ADO default filter might break if issues not audited and removed between syncs

### ISSUE THREAD

**Issue by itkaa** [fortify-ps/FortifyBugTrackerUtility#60]
In some situations, a finding might make it into a scan and then get fixed and removed, a new scan runs and the issue is marked as "Fix Validated" on FoD and disappears from the FoD dashboard. 

However, all the other attributes of the issue indicate that it is open so the utility will submit it although it would now be fixed and not require submission.

To fix this use the status!='Fix Validated' condition in the isVulnerabilityOpenExpression property.

```
<property name="isVulnerabilityOpenExpression"><value><![CDATA[
			closedStatus==false && isSuppressed==false && status!='Fix Validated'
		]]></value></property>
```

**Comment by rsenden** [comment]
Thanks for reporting this. I have updated the value for `isVulnerabilityOpenExpression` in the sample configuration files; this will be included with the next release.

**Comment by rsenden** [comment]
https://github.com/fortify-ps/FortifyBugTrackerUtility/releases/tag/4.3
