### ISSUE TITLE
FOD 4.5 missed results for integration into Jira 8.20.1

### ISSUE THREAD

**Issue by DLearning-TSL** [fortify-ps/FortifyBugTrackerUtility#67]
Hello,

I'm running an FoD scanner that dumps it's tickets into an on prem Jira instance (8.20.1 on Linux), I'm using the utility (4.5) to pull the results in, but it has missed pulling over a dozen of them from FoD.  The missed results are from the static and dynamic scan, and range in priority from medium to high vulnerabilities.  I do not see a commonality in the vulnerabilities and so I do not know where to start in finding out why they did not integrate into Jira tickets. Any advice would be appreciated.

Regards
D

**Comment by rsenden** [comment]
Hi,

Can you please share the output of the utility, your FoDToJira.xml configuration file (if you customized it), and the number of critical, high, medium and low vulnerabilities in the release where you're experiencing this issue? Are you experiencing this only on a particular release, or is this a generic problem?

Note that the default configuration file only exports Critical and High issues, and only non-suppressed issues. Also any issue that already has a bug link associated to it will be skipped.

Regards,
Ruud

**Comment by DLearning-TSL** [comment]
Ruud,

Thank you for the response, it pointed me in the right direction to resolve this and I appreciate it.  I believe our .xml was over written when we rebuilt the instance and I believe that was the root of the problem.  Thank you very much for assistance.

Derek

**Comment by rsenden** [comment]
@DLearning-TSL, thanks for the update. I'll close the issue then.
