### ISSUE TITLE
Links to FoD/SSC prep pages in docs don't work.  (Capitalization mismatch)

### ISSUE THREAD

**Issue by bdaddy-mit** [fortify-ps/FortifyBugTrackerUtility#77]
https://github.com/fortify-ps/FortifyBugTrackerUtility/blob/3107fce8b9c5334fe9c3a06aa82fc529659619aa/bugtracker/src/site/site.xml#L35-L36

These capitalization of these hyperlinks appear to not match the names of the actual target HTML files.  For example, this is what I get when I click on "Preperations -> SSC" in a web browser:

![image](https://github.com/fortify-ps/FortifyBugTrackerUtility/assets/116455354/012832da-cce3-4697-8036-4ceccc2b0836)

**Comment by rsenden** [comment]
Thanks for reporting this, I guess most users read the documentation from case-insensitive Windows filesystems. I've now fixed the links, new release should be posted later today.
